major-version-bump-message: \+semver:\s(breaking|major)
minor-version-bump-message: \+semver:\s(feature|minor)
patch-version-bump-message: \+semver:\s(fix|hotfix|patch)
branches:
  main:
    increment: none
    prevent-increment:
      of-merged-branch: true
  feature:
    increment: Minor
    regex: ^feature(s)?[/-](?<BranchName>.+)
  hotfix:
    increment: Patch
    regex: ^hotfix(es)?[/-](?<BranchName>.+)
  fix:
    increment: Patch
    regex: ^fix(es)?[/-](?<BranchName>.+)

