name: Build container
run-name: Build container by @${{ gitea.actor }}
on:
  push:
    branches:
      - hotfix/*
      - hotfixes/*
      - fix/*
      - fixes/*
      - feature/*
      - features/*
      - main
    paths-ignore:
      - "README.md"

jobs:
  Lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.12.9
    steps:
      - name: Clone repo
        run: git clone --branch ${{ gitea.ref_name }} $REPO_URL repbot > /dev/null
        env:
          REPO_URL: https://gitea.bogan.io/${{ gitea.repository }}

      - name: Setup tools
        run: pip install -r requirements.txt

      - name: Style check
        run: black reputable_bot/
      
      - name: Lint check
        run: pylint reputable_bot/

